name: Dart Cached (faster)

on:
  push:
    branches: [ "main" , "master" , "test" , "test2" , "aloealez" , "aloealez2" , "aloealez-actions-test" , "aloealez-5" ]
  pull_request:
    branches: [ "main" , "master" , "test" , "test2" , "aloealez" , "aloealez2" , "aloealez-actions-test" , "aloealez-5" ]

env:
  flutter_version: "3.32.8"
  java_version: "17.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ env.java_version }}
          distribution: temurin

      - name: Cache Flutter
        uses: actions/cache@v4.2.3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Debug Build
        run: flutter build apk --debug

      - name: Upload build apk
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Debug-apk-cached
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 3
